### ISSUE TITLE
brew uninstall Node.js & Mac

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/Gatsby#9]
# brew uninstall Node.js & Mac

```sh
$ which node
# /usr/local/bin/node

$ brew uninstall --force node

```

https://codedamn.com/news/nodejs/how-to-uninstall-node-js#Uninstalling_the_Nodejs_on_Mac

??? ❌

```sh
$ brew uninstall --force node
Traceback (most recent call last):
	11: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'
	10: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative'
	 9: from /usr/local/Homebrew/Library/Homebrew/global.rb:29:in `<top (required)>'
	 8: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /usr/local/Homebrew/Library/Homebrew/os.rb:3:in `<top (required)>'
	 5: from /usr/local/Homebrew/Library/Homebrew/os.rb:21:in `<module:OS>'
	 4: from /usr/local/Homebrew/Library/Homebrew/os/mac.rb:58:in `prerelease?'
	 3: from /usr/local/Homebrew/Library/Homebrew/os/mac.rb:24:in `version'
	 2: from /usr/local/Homebrew/Library/Homebrew/os/mac.rb:24:in `new'
	 1: from /usr/local/Homebrew/Library/Homebrew/os/mac/version.rb:26:in `initialize'
/usr/local/Homebrew/Library/Homebrew/version.rb:368:in `initialize': Version value must be a string; got a NilClass () (TypeError)
➜  ~ 




```
作者：xgqfrms
链接：https://www.cnblogs.com/xgqfrms/p/13213651.html
来源：https://www.cnblogs.com
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
            ©xgqfrms 2012-2022
www.cnblogs.com 发布文章使用：只允许注册用户才可以访问！
     原创文章，版权所有©️xgqfrms, 禁止转载 🈲️，侵权必究⚠️！

**Comment by xgqfrms** [comment]
https://www.cnblogs.com/xgqfrms/p/16868027.html#5121237

https://github.com/xgqfrms/Gatsby-Tutorials-All-In-One/issues/9

https://github.com/xgqfrms/cnblogs/issues/19
